"""empty message

Revision ID: 0b1a56be986a
Revises: 664e8a5491e5
Create Date: 2020-08-15 22:59:56.720092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1a56be986a'
down_revision = '664e8a5491e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('n_pages', sa.Integer(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('isbn_13', sa.String(), nullable=True),
    sa.Column('isbn_10', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('cover_img', sa.String(), nullable=True),
    sa.Column('genres', sa.String(), nullable=True),
    sa.Column('top_tfidf_words', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
